name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  pull-requests: write
  packages: read

jobs:
  release-please:
    runs-on: ubuntu-24.04
    outputs:
      release_created: ${{ steps.rp.outputs.releases_created }}

    steps:
      - name: Release please
        id: rp
        uses: google-github-actions/release-please-action@5792afc6b46e9bb55deda9eda973a18c226bc3fc # v4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          default-branch: main
